language: java
sudo: false
cache:
  directories:
    - $HOME/.m2

language: java
jdk:
  - openjdk7
  - oraclejdk8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give time for xvfb to start
